export const cakesGallery = [
  {
    src: "/gallery-cakes/1.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/1.png",
  },
  {
    src: "/gallery-cakes/2.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/2.png",
  },
  {
    src: "/gallery-cakes/3.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/3.png",
  },
  {
    src: "/gallery-cakes/4.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/4.png",
  },
  {
    src: "/gallery-cakes/5.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/5.png",
  },
  {
    src: "/gallery-cakes/6.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/6.png",
  },
  {
    src: "/gallery-cakes/7.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/7.png",
  },
  {
    src: "/gallery-cakes/8.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/8.png",
  },
  {
    src: "/gallery-cakes/9.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/9.png",
  },
  {
    src: "/gallery-cakes/10.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/10.png",
  },
  {
    src: "/gallery-cakes/11.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/11.png",
  },
  {
    src: "/gallery-cakes/12.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/12.png",
  },
  {
    src: "/gallery-cakes/1.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/1.png",
  },
  {
    src: "/gallery-cakes/2.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/2.png",
  },
  {
    src: "/gallery-cakes/3.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/3.png",
  },
  {
    src: "/gallery-cakes/4.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/4.png",
  },
  {
    src: "/gallery-cakes/5.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/5.png",
  },
  {
    src: "/gallery-cakes/6.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/6.png",
  },
  {
    src: "/gallery-cakes/7.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/7.png",
  },
  {
    src: "/gallery-cakes/8.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/8.png",
  },
  {
    src: "/gallery-cakes/9.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/9.png",
  },
  {
    src: "/gallery-cakes/10.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/10.png",
  },
  {
    src: "/gallery-cakes/11.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/11.png",
  },
  {
    src: "/gallery-cakes/12.png",
    alt: "obrázek dortu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-cakes/12.png",
  },
];

export const dessertsGallery = [
  {
    src: "/gallery-desserts/1.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/1.png",
  },
  {
    src: "/gallery-desserts/2.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/2.png",
  },
  {
    src: "/gallery-desserts/3.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/3.png",
  },
  {
    src: "/gallery-desserts/4.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/4.png",
  },
  {
    src: "/gallery-desserts/5.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/5.png",
  },
  {
    src: "/gallery-desserts/6.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/6.png",
  },
  {
    src: "/gallery-desserts/7.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/7.png",
  },
  {
    src: "/gallery-desserts/8.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/8.png",
  },
  {
    src: "/gallery-desserts/9.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/9.png",
  },
  {
    src: "/gallery-desserts/10.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/10.png",
  },
  {
    src: "/gallery-desserts/11.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/11.png",
  },
  {
    src: "/gallery-desserts/12.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/12.png",
  },
  {
    src: "/gallery-desserts/13.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/13.png",
  },
  {
    src: "/gallery-desserts/14.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/14.png",
  },
  {
    src: "/gallery-desserts/15.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/15.png",
  },
  {
    src: "/gallery-desserts/16.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/16.png",
  },
  {
    src: "/gallery-desserts/17.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/17.png",
  },
  {
    src: "/gallery-desserts/18.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/18.png",
  },
  {
    src: "/gallery-desserts/19.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/19.png",
  },
  {
    src: "/gallery-desserts/20.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/20.png",
  },
  {
    src: "/gallery-desserts/1.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/1.png",
  },
  {
    src: "/gallery-desserts/2.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/2.png",
  },
  {
    src: "/gallery-desserts/3.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/3.png",
  },
  {
    src: "/gallery-desserts/4.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/4.png",
  },
  {
    src: "/gallery-desserts/5.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/5.png",
  },
  {
    src: "/gallery-desserts/6.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/6.png",
  },
  {
    src: "/gallery-desserts/7.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/7.png",
  },
  {
    src: "/gallery-desserts/8.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/8.png",
  },
  {
    src: "/gallery-desserts/9.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/9.png",
  },
  {
    src: "/gallery-desserts/10.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/10.png",
  },
  {
    src: "/gallery-desserts/11.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/11.png",
  },
  {
    src: "/gallery-desserts/12.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/12.png",
  },
  {
    src: "/gallery-desserts/13.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/13.png",
  },
  {
    src: "/gallery-desserts/14.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/14.png",
  },
  {
    src: "/gallery-desserts/15.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/15.png",
  },
  {
    src: "/gallery-desserts/16.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/16.png",
  },
  {
    src: "/gallery-desserts/17.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/17.png",
  },
  {
    src: "/gallery-desserts/18.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/18.png",
  },
  {
    src: "/gallery-desserts/19.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/19.png",
  },
  {
    src: "/gallery-desserts/20.png",
    alt: "obrázek dezertu v galerii",
    media_type: "image",
    type: "image",
    thumbnail: "/gallery-desserts/20.png",
  },
];
